server:
  port: 8081

spring:
    application:
        name: center_2
    datasource:
      url: mongodb://localhost:27017/center_2

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
